### PR TITLE
Honu operators can now be used normally in Racket.

### PR DESCRIPTION
**Pull request by mromyers**
More can be done, but it's a start.

```
#lang racket
(require enforest
         enforest/arithmetic)

(define (f x)
  (unparsed-begin
    3 * x ^ 2 + 1 ))
(define (g x)
  (+ (* 3 (^ x 2)) 1))

(for/and ([i (in-range 1000)])
  (unparsed-begin
   g (#%parens i) = f (#%parens i)))
```

### CODE REVIEW

**Comment by kazzmir** [comment]
This is good but if users want to use honu syntax in Racket programs the form should start with 'honu' or something.

```
(honu 3 + x)
```

**Comment by mromyers** [comment]
I agree, but I think that's better reserved for a function that steps through the sub-expressions, adding #%parens #%braces #%brackets etc based on the 'paren-shape syntax property (and possibly something tricky for %comma and %semicolon), then passes to honu-unparsed-begin.

**Comment by kazzmir** [comment]
I think maybe you can solve this by using the scribble reader. @honu{2 + 3
- f(x)}. I think the stuff in between the {} gets passed as a raw string to
  the 'honu' function, then you can call honu-read-syntax.

**Comment by mromyers** [comment]
I like it!

**Comment by elibarzilay** [comment]
The first step would be what Jon described, then the obvious second step would be to change `honu` into a macro so the reading & parsing (and honu macros) are all done at compile-time.

(And this is a perfect use of the scribble reader, BTW; one that I described on many occasions but didn't get used much so far.)

**Comment by soegaard** [comment]
Did this ever get applied? If I recall correctly it was need to get #%app to work.
   https://github.com/plt/racket/pull/695/files

Found it!  (I got confused by the fact that the the original file was gone)

**Pull request merged**
